### ISSUE TITLE
The question of GPU loss

### ISSUE THREAD

**Issue by reborn-113** [sucheta19/Text-Classification-Using-CNN#1]
Hi,author:
When I recreated your network, I found,
In GPU FP32 mode, loss does not converage occasionally during training.
Afier the first epoch, it lasted at 1.3864.
Then, the loss jitter occurs.

**Comment by sucheta19** [comment]
Hi,
I have forked this repository from https://github.com/chaitjo/character-level-cnn
The original repo is https://github.com/mhjabreel/CharCnn_Keras
Please raise this issue there, they might be better suited to answer your question.
